# This is a generated file. Not intended for manual editing.
services:
  dndtracker:
    build:
      context: "/Users/gabrieletoffanin/Developer/rider/DNDTracker.Api"
      dockerfile: "DNDTracker/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/DNDTracker.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "dndtracker:dev"
    ports: []
    volumes:
    - "/Users/gabrieletoffanin/Developer/rider/DNDTracker.Api/DNDTracker:/app:rw"
    - "/Users/gabrieletoffanin/Developer/rider/DNDTracker.Api:/src:rw"
    - "/Users/gabrieletoffanin/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
