apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dndtracker.fullname" . }}
  labels:
    {{- include "dndtracker.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}