version: "3.8"

volumes:
  postgres-data:
  rabbitmq-data:
  datadogdata:

networks:
  default:
    name: dndtrackernetwork
    external: false

services:
  # DNDTracker Application Services
  dndtracker.api:
    image: dndtracker.main
    build:
      context: .
      dockerfile: src/DNDTracker.Main/Dockerfile
    ports:
      - "5169:8080"
      - "8081:8081"
    labels:
      - com.datadoghq.tags.env=development
      - com.datadoghq.tags.service=dndtracker-api
      - com.datadoghq.tags.version=1.0.0
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=dndtracker;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Scalar__Enabled=true
      - DD_API_KEY=a40197fd792b2dd09993b36b3ef816f6
      - DD_SITE=datadoghq.eu
      - DD_ENV=development
      - DD_SERVICE=dndtracker-api
      - DD_VERSION=1.0.0
      - DD_GIT_REPOSITORY_URL=github.com/gabrieletoffanin/dndtracker
      - DD_AGENT_HOST=datadog-agent
      - DD_AGENT_PORT=8126
      - DD_TRACE_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_DATA_STREAMS_ENABLED=true
      - DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED=true
      - DD_APPSEC_ENABLED=true
      - DD_IAST_ENABLED=true
      - DD_APPSEC_SCA_ENABLED=true
      - DD_TRACE_SAMPLE_RATE=1
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
      - CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
      - DD_DOTNET_TRACER_HOME=/opt/datadog
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - default

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dndtracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - default

  # Datadog Agent
  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - datadogdata:/opt/datadog-agent/run
    ports:
      - "127.0.0.1:8126:8126/tcp"
    environment:
      - DD_API_KEY=a40197fd792b2dd09993b36b3ef816f6
      - DD_SITE=datadoghq.eu
    networks:
      - default
