metricbeat.name: metricbeat01
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: '${ELASTIC_HOSTS:elasticsearch:9200}'
  username: '${ELASTIC_USER:elastic}'
  password: '${ELASTIC_PASSWORD:changeme}'
  protocol: https
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]

setup.kibana:
  host: '${KIBANA_HOSTS:kibana:5601}'

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644
