integrations:
  - name: nri-rabbitmq
    env:
      METRICS: true
      INVENTORY: true
      HOSTNAME: "{{RABBITMQ_MANAGEMENT_HOST}}"
      PORT: "{{RABBITMQ_MANAGEMENT_PORT}}"
      USERNAME: "{{RABBITMQ_MANAGEMENT_USERNAME}}"
      PASSWORD: "{{RABBITMQ_MANAGEMENT_PASSWORD}}"
      USE_SSL: false
      QUEUES_REGEXES: '[".*"]'
      EXCHANGES_REGEXES: '[".*"]'
      VHOSTS_REGEXES: '[".*"]'
    interval: 15s
    labels:
      environment: development
      service: dndtracker
    inventory_source: config/rabbitmq
