// <auto-generated />
using System;
using DNDTracker.Outbound.PostgresDb.Database.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DNDTracker.Outbound.PostgresDb.Migrations
{
    [DbContext(typeof(DNDTrackerPostgresDbContext))]
    [Migration("20260816215502_ExpandMonsterSheets")]
    partial class ExpandMonsterSheets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.ActiveCombatModel", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("integer");

                    b.HasKey("CampaignId");

                    b.ToTable("ActiveCombatModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CampaignMemberModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignMemberModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CampaignModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampaignImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CampaignModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CampaignTimelineEntryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignTimelineEntryModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CombatantConditionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CombatantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RemainingRounds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CombatantId");

                    b.ToTable("CombatantConditionModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CombatantStateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveCombatCampaignId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("HideHitPointsFromPlayers")
                        .HasColumnType("boolean");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemporaryHitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCombatCampaignId");

                    b.ToTable("CombatantStateModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.EquipmentItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("EquipmentItemModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.HeroConditionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RemainingRounds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("HeroConditionModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.HeroModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Alignment")
                        .HasColumnType("integer");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("HitDice")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNonPlayerCharacter")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Race")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("TemporaryHitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("HeroModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.InventoryItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("InventoryItemModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.LocationResourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MapUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("LocationResourceModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.LootResourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMagicItem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("LootResourceModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.MonsterStatBlockModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<string>("BonusActions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChallengeRating")
                        .HasColumnType("integer");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("InitiativeModifier")
                        .HasColumnType("integer");

                    b.Property<string>("LairActions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LegendaryActions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reactions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<string>("Spells")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statistics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("MonsterStatBlockModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.NpcResourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("NpcResourceModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.QuestResourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("QuestResourceModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.SessionLogEntryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DungeonMasterNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("SessionLogEntryModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.SpellModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CastingTime")
                        .HasColumnType("text");

                    b.Property<string>("Components")
                        .HasColumnType("text");

                    b.Property<string>("Concentration")
                        .HasColumnType("text");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<bool>("IsRitual")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Range")
                        .HasColumnType("text");

                    b.Property<string>("Save")
                        .HasColumnType("text");

                    b.Property<string>("School")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpellModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.SpellSlotUsageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SlotsSpent")
                        .HasColumnType("integer");

                    b.Property<int>("SlotsTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("SpellSlotUsageModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.SpellbookEntryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("boolean");

                    b.Property<int>("SpellId")
                        .HasColumnType("integer");

                    b.Property<string>("SpellName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("SpellbookEntryModel");
                });

            modelBuilder.Entity("HeroModelSpellModel", b =>
                {
                    b.Property<Guid>("HeroesId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpellsId")
                        .HasColumnType("integer");

                    b.HasKey("HeroesId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("HeroModelSpellModel");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.ActiveCombatModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithOne("ActiveCombat")
                        .HasForeignKey("DNDTracker.Vocabulary.Models.ActiveCombatModel", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CampaignMemberModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("Members")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CampaignTimelineEntryModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CombatantConditionModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CombatantStateModel", "Combatant")
                        .WithMany("Conditions")
                        .HasForeignKey("CombatantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combatant");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CombatantStateModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.ActiveCombatModel", "ActiveCombat")
                        .WithMany("InitiativeOrder")
                        .HasForeignKey("ActiveCombatCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCombat");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.EquipmentItemModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.HeroModel", "Hero")
                        .WithMany("Equipment")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.HeroConditionModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.HeroModel", "Hero")
                        .WithMany("Conditions")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.HeroModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("Heroes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.InventoryItemModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.HeroModel", "Hero")
                        .WithMany("Inventory")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.LocationResourceModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("Locations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.LootResourceModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("Loot")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.MonsterStatBlockModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("MonsterLibrary")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.NpcResourceModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("Npcs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.QuestResourceModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("Quests")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.SessionLogEntryModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.CampaignModel", "Campaign")
                        .WithMany("SessionLogs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.SpellSlotUsageModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.HeroModel", "Hero")
                        .WithMany("SpellSlots")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.SpellbookEntryModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.HeroModel", "Hero")
                        .WithMany("Spellbook")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("HeroModelSpellModel", b =>
                {
                    b.HasOne("DNDTracker.Vocabulary.Models.HeroModel", null)
                        .WithMany()
                        .HasForeignKey("HeroesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDTracker.Vocabulary.Models.SpellModel", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.ActiveCombatModel", b =>
                {
                    b.Navigation("InitiativeOrder");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CampaignModel", b =>
                {
                    b.Navigation("ActiveCombat");

                    b.Navigation("Heroes");

                    b.Navigation("Locations");

                    b.Navigation("Loot");

                    b.Navigation("Members");

                    b.Navigation("MonsterLibrary");

                    b.Navigation("Npcs");

                    b.Navigation("Quests");

                    b.Navigation("SessionLogs");

                    b.Navigation("TimelineEntries");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.CombatantStateModel", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("DNDTracker.Vocabulary.Models.HeroModel", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Equipment");

                    b.Navigation("Inventory");

                    b.Navigation("SpellSlots");

                    b.Navigation("Spellbook");
                });
#pragma warning restore 612, 618
        }
    }
}
